[package]
name = "h12tiny-client"
version = "0.1.1"
edition = "2021"
rust-version = "1.85"
description = "Direct-origin HTTP client for h12tiny"
license = "MIT OR Apache-2.0"

[features]
default = []
http1 = ["dep:async-io", "dep:async-net", "hyper/client", "hyper/http1"]
http2 = ["dep:async-io", "dep:async-net", "hyper/client", "hyper/http2"]
tls = ["dep:futures-rustls", "dep:rustls", "dep:rustls-graviola", "dep:webpki-roots"]

[dependencies]
async-io = { workspace = true, optional = true }
async-net = { workspace = true, optional = true }
futures-channel = { workspace = true }
futures-io = { workspace = true }
futures-rustls = { workspace = true, optional = true }
futures-util = { workspace = true }
h12tiny-core = { version = "0.1.0", path = "../h12tiny-core", default-features = false }
h12tiny-client-normalize = { version = "0.1.0", path = "../h12tiny-client-normalize" }
http = { workspace = true }
http-body = { workspace = true }
hyper = { workspace = true }
rustls = { workspace = true, optional = true }
rustls-graviola = { workspace = true, optional = true }
webpki-roots = { workspace = true, optional = true }

[dev-dependencies]
async-io = { workspace = true }
futures-lite = { workspace = true }
smol = "2"
