[package]
name = "h12tiny-util"
version = "0.2.0"
edition = "2021"
rust-version = "1.85"
description = "Protocol-neutral HTTP body conveniences for h12tiny"
license = "MIT OR Apache-2.0"

[features]
default = []
json = ["dep:miniserde"]

[dependencies]
async-io = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
futures-io = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = "0.1.5"
pin-project-lite = { workspace = true }
miniserde = { version = "0.1.46", optional = true }

[dev-dependencies]
futures-lite = { workspace = true }
